# Generated by Django 5.2.11 on 2026-02-19 08:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Název nápoje')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cena (Kč)')),
            ],
        ),
        migrations.CreateModel(
            name='StaffUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Uživatelské jméno')),
                ('password', models.CharField(max_length=128, verbose_name='Heslo (hash)')),
                ('token', models.CharField(blank=True, max_length=64, unique=True, verbose_name='API token')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID stolu')),
                ('number', models.IntegerField(unique=True, verbose_name='Číslo stolu')),
                ('seats', models.IntegerField(verbose_name='Počet míst')),
            ],
        ),
        migrations.CreateModel(
            name='DrinkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Název typu nápoje')),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='zakaznici.drink', verbose_name='Nápoj')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID objednávky')),
                ('status', models.CharField(choices=[('NEW', 'Nová'), ('ACCEPTED', 'Přijatá'), ('REJECTED', 'Odmítnutá'), ('FINISHED', 'Dokončená'), ('MISSED', 'Propáslá (10m)'), ('MISSED_DEADLINE', 'Nestihnutá (15m)')], default='NEW', max_length=20, verbose_name='Stav objednávky')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datum a čas vytvoření')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Datum a čas přijetí')),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zakaznici.drink', verbose_name='Nápoj')),
                ('drink_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zakaznici.drinktype', verbose_name='Typ nápoje')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='zakaznici.table', verbose_name='Stůl')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
